version: '3'
services:
  playwright:
    build:
      context: ./e2e
      cache_from:
        - type=gha
      cache_to:
        - type=gha
    volumes:
      - type: bind
        source: playwright-report/
        target: /app/playwright-report
    network_mode: 'host'
    depends_on: [web]
