version: '3'
services:
  firebase:
    build:
      context: .
      dockerfile: firebase.Dockerfile
    ports:
      - '9099:9099'
      - '9000:9000'
      - '4000:4000'
  yjs:
    build:
      context: .
      dockerfile: yjs.Dockerfile
    ports:
      - '1234:1234'
  execute:
    build:
      context: execute
    ports:
      - '1235'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST="firebase:9099"
    ports:
      - '3000:3000'
      - '127.0.0.1:9229:9229'
    volumes:
      - type: bind
        source: src/
        target: /app/src
      - type: bind
        source: public/
        target: /app/public
      - type: bind
        source: pages/
        target: /app/pages
      - type: bind
        source: patches/
        target: /app/patches
    depends_on: [firebase, yjs, execute]
