name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # CHeck out defult branhc
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0 # Fetch every bit of history

      # Set up Vercel creds
      - name: Set up Git
        run: |
          git config user.name "AlgoPro"
          git config user.email "info@algopro.hu"

          # Fetch relevant branches
          git fetch origin production:production

          # Create production-update branch
          git checkout production
          # Merge and squash changes from main

          git merge --squash origin/master
          git commit -m "Deploy to production"

      # Create pullrequest
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.VERCEL_IDE_DEPLOY_TOKEN }}
          branch: production-update
          committer: 'AlgoPro <info@algopro.hu>'
          title: 'Deploy to Production'
          branch-suffix: timestamp
          body: 'This PR contains the latest changes from main to be deployed to production.'
